name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs-version:
          - "29.4"
          - "30.2"
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - name: Install test dependencies
        run: make install-test-deps
      - name: Compile and test
        run: make clean all
      - name: Compile extensions
        run: make compile-all-extensions
